### ISSUE TITLE
font-size: normal;

### ISSUE THREAD

**Issue by NateWeiler** [Thommond/Thommond.github.io#2]
If you didn't put this the font size by default for normal text, like paragraphs, is 16px (16px=1emhttps://github.com/Thommond/Thommond.github.io/blob/c3efe698bbcbcbc93f3f0db6e977651ceefec18b/styles.css#L16

**Comment by zachfedor** [comment]
@NateWeiler I'm not sure what the issue is here

**Comment by Thommond** [comment]
I dont feel I need font size normal, I can specify the font on other tags. Thanks though!
